import os
import yaml

articles = [
    {
        "slug": "reverse-mortgages-multi-family-homes-duplex",
        "title": "Reverse Mortgages for Multi-Family Homes (Duplex, Triplex)",
        "description": "Discover how you can use a reverse mortgage to access equity in a 2-to-4 unit multi-family property.",
        "category": "property-types",
        "date": "2024-01-18",
        "takeaways": [
            "You can get a HECM on a 2-unit, 3-unit, or 4-unit property.",
            "You must live in one of the units as your primary residence.",
            "Rental income from the other units can help you qualify for the loan."
        ],
        "content": """
Most people associate reverse mortgages exclusively with single-family suburban houses. However, the Federal Housing Administration (FHA) allows seniors to use a Home Equity Conversion Mortgage (HECM) on multi-family properties.

If you own a duplex, triplex, or a four-plex, you have a unique opportunity to access your home equity while continuing to generate rental income.

## The Primary Residence Requirement

The golden rule for getting a reverse mortgage on a multi-family property is occupancy. 

You cannot use a HECM on an investment property where you are an absentee landlord. **You must live in one of the units as your primary residence.** If you own a triplex, you must occupy Unit A, and you are free to rent out Unit B and Unit C. 

If you ever move out of your primary unit (e.g., to a nursing home or to live with your children), the entire reverse mortgage will become Due and Payable, and you will be forced to sell the building.

## Using Rental Income to Qualify

Following the 2015 Financial Assessment rules, all reverse mortgage applicants must prove they have the income to continue paying their property taxes and homeowners insurance.

If you own a multi-family building, the FHA allows lenders to count the **verifiable rental income** generated by the other units toward your financial qualification. 

If your Social Security alone is not enough to cover the massive property tax bill on a 4-unit building in Chicago, the monthly rent checks you receive from your three tenants will usually push your income high enough to pass the Financial Assessment, avoiding a mandatory Life Expectancy Set-Aside (LESA).

## Maintenance Requirements

Being a landlord comes with maintenance responsibilities. A reverse mortgage adds an extra layer of strictness. 

The FHA requires the entire property—not just your unit—to be maintained to minimum safety standards. If a tenant trashes one of your rental units, or if the roof over the rental units starts leaking, you must repair it. Failing to maintain the property can trigger a default on your reverse mortgage.
"""
    },
    {
        "slug": "reverse-mortgage-manufactured-mobile-homes",
        "title": "Can You Get a Reverse Mortgage on a Manufactured Home?",
        "description": "Learn the strict FHA guidelines for securing a reverse mortgage on a manufactured or mobile home.",
        "category": "property-types",
        "date": "2024-01-20",
        "takeaways": [
            "The home must have been built after June 15, 1976.",
            "You must own the land the home sits on; trailer park lot leases do not qualify.",
            "The home must be permanently affixed to an FHA-approved foundation."
        ],
        "content": """
Many seniors choose to retire in manufactured housing due to its affordability and low maintenance. If you own a manufactured home and want a reverse mortgage, the process is possible, but the FHA guidelines are incredibly strict.

Lenders refer to manufactured housing as "mobile homes," though the legal definition depends heavily on when and how the home was built.

## The Age of the Home

The most inflexible rule regards the manufacturing date. 
To qualify for a Home Equity Conversion Mortgage (HECM), **the manufactured home must have been built after June 15, 1976.** 

This date marks the implementation of the HUD Manufactured Home Construction and Safety Standards. If your home was built in 1974, it is entirely ineligible for any FHA-insured loan, no matter how many upgrades you have made. You must locate the HUD certification tags (usually a red metal plate bolted to the outside of the home) to prove the manufacturing date.

## Land Ownership vs. Leased Lots

The second massive hurdle is land ownership.

A reverse mortgage is a real estate loan. Therefore, **you must own the land underneath the manufactured home.** 

If your home is located in a mobile home park where you pay a monthly "lot fee" or "pad lease" to a park owner, you cannot get a reverse mortgage. You do not own the real estate; you only own the physical structure, which is considered personal property (like a car) rather than real estate.

## Foundation and Structural Modifications

To qualify for a reverse mortgage, the manufactured home must be **permanently affixed to a foundation** that meets FHA engineering standards. The axles and towing tongue must be permanently removed.

Furthermore, if you have built additions onto the home (like a massive wrap-around porch, a structural sunroom, or an attached garage), you must hire a licensed structural engineer to certify that the additions do not compromise the structural integrity of the original manufactured home frame. 

Because of these stringent requirements, many lenders simply refuse to underwrite manufactured homes, so you may need to shop around for a specialist broker.
"""
    },
    {
        "slug": "fha-condo-approval-reverse-mortgage",
        "title": "FHA Condo Approval Secrets for Reverse Mortgages",
        "description": "How to get a reverse mortgage if you live in a condominium, including FHA project approval and Spot Approvals.",
        "category": "property-types",
        "date": "2024-01-22",
        "takeaways": [
            "The entire condo complex must usually be FHA-approved.",
            "You can apply for a Single-Unit Approval (Spot Approval) if the complex is not approved.",
            "The HOA's financial health will be heavily scrutinized by the lender."
        ],
        "content": """
Condominiums are incredibly popular among retirees seeking a maintenance-free lifestyle. However, getting a reverse mortgage on a condo is significantly more difficult than getting one on a single-family house.

This is because the FHA does not just evaluate your individual unit; they evaluate the financial and legal health of the entire Condominium Homeowners Association (HOA).

## Full Project Approval

Historically, to get a Home Equity Conversion Mortgage (HECM) on a condo, the entire condo complex had to be on the **HUD Approved Condominium list**. 

If your HOA had let their FHA certification expire (which is common, as it costs money and requires an audit every few years), you could not get a reverse mortgage, period.

## The Return of "Spot Approvals"

In 2019, HUD introduced a massive rule change that saved condo owners: **Single-Unit Approvals** (often called Spot Approvals).

If your condo complex is not FHA-approved, your lender can submit a massive packet of documents to HUD to get just *your specific unit* approved for a reverse mortgage.

## The HOA Document Nightmare

While Spot Approvals are a lifesaver, they require the intense cooperation of your HOA board or property management company. Your reverse mortgage lender will require the HOA to fill out an exhaustive questionnaire and provide:
1. The HOA's current budget and balance sheet.
2. Proof that at least 10% of the HOA budget goes into a reserve account for future repairs.
3. Proof that no more than 15% of the units are 60+ days delinquent on their HOA dues.
4. Proof of a master insurance policy with sufficient hazard and liability coverage.
5. Details on any pending litigation against the HOA.

If your HOA is poorly managed, underfunded, or currently being sued by a contractor, the FHA will deny your Spot Approval, and your reverse mortgage will be declined. 

Before paying hundreds of dollars for a reverse mortgage appraisal, always have your loan officer run a preliminary check on your HOA's financial health.
"""
    },
    {
        "slug": "jumbo-reverse-mortgages-high-value-homes",
        "title": "Jumbo Reverse Mortgages: Pros and Cons for High-Value Homes",
        "description": "If your home is worth more than $1.14 million, learn why a proprietary Jumbo reverse mortgage might be a better fit than a HECM.",
        "category": "property-types",
        "date": "2024-01-24",
        "takeaways": [
            "The FHA HECM lending limit is capped at $1,149,825.",
            "Jumbo reverse mortgages allow you to access equity up to $4 million.",
            "Jumbos do not charge the expensive upfront FHA Mortgage Insurance Premium."
        ],
        "content": """
The federally insured Home Equity Conversion Mortgage (HECM) is the standard for 90% of the reverse mortgage market. However, the HECM program has a fatal flaw for seniors living in extremely expensive real estate markets like California, New York, or Hawaii.

The FHA imposes a strict national **Maximum Claim Amount limit (currently $1,149,825 for 2024).**

If your home in San Francisco is appraised at $3 million, the FHA treats it as if it is only worth $1.14 million. You leave nearly two million dollars of equity on the table, completely inaccessible.

The solution is the **Proprietary Jumbo Reverse Mortgage**.

## What is a Jumbo Reverse Mortgage?

Jumbo reverse mortgages are private loans backed by massive banks and investment firms, not the federal government. Because they operate outside FHA rules, lenders can set their own lending limits—often allowing you to access equity on homes valued up to $4 million or even $10 million.

## The Advantages of Jumbo Loans

1. **Access to More Cash:** If you have a $2.5 million home, a Jumbo loan might allow you to draw $1 million in tax-free cash, compared to a maximum of roughly $400k on a HECM.
2. **No FHA Mortgage Insurance:** HECM loans require you to pay a massive upfront Mortgage Insurance Premium (2% of the home's value) to the FHA. Jumbo loans are private; they do not charge this premium, saving you tens of thousands of dollars in closing costs.
3. **Condo Flexibility:** Jumbo lenders do not require strict FHA condo project approval. If your luxury condo was rejected by the FHA, a Jumbo lender might approve it immediately.

## The Disadvantages

1. **Higher Interest Rates:** Because Jumbo lenders do not have the safety net of the federal government, they take on more risk. They compensate for this by charging higher interest rates than a standard HECM.
2. **Fewer Payout Options:** HECM loans are famous for their flexible Line of Credit that grows over time. Jumbo loans typically require you to take the money as a single massive lump sum at closing, which begins compounding interest immediately. 
3. **Stricter Age Requirements:** While you can get a HECM at age 62, many Jumbo lenders require the youngest borrower to be at least 60, and sometimes they offer worse loan-to-value ratios unless you are in your 70s.
"""
    },
    {
        "slug": "reverse-mortgages-in-new-york-co-op-laws",
        "title": "Reverse Mortgages in New York: Co-Op Laws Explained",
        "description": "An overview of the legal landscape for obtaining a reverse mortgage on a housing cooperative (co-op) in New York State.",
        "category": "state-guides",
        "date": "2024-01-26",
        "takeaways": [
            "Historically, co-ops were entirely ineligible for reverse mortgages.",
            "New York recently passed legislation allowing reverse mortgages on co-ops.",
            "You cannot use an FHA HECM for a co-op; you must use a proprietary private loan."
        ],
        "content": """
For decades, seniors living in New York City faced a massive financial injustice: if they lived in a condominium, they could get a reverse mortgage, but if they lived in a housing cooperative (a co-op), they were banned from the program.

Given that a massive percentage of NYC real estate consists of co-ops, thousands of house-rich, cash-poor seniors were locked out of their equity.

## Why Were Co-Ops Banned?

The issue comes down to legal definitions of real estate. When you buy a house or a condo, you receive a deed to the physical property. A reverse mortgage is a lien placed against that deed.

When you "buy" a co-op, you do not actually buy real estate. You buy shares in a corporation that owns the entire building, and in return, you are granted a proprietary lease to live in a specific unit. Because you own *shares* (personal property) rather than real estate, traditional mortgage laws do not neatly apply, and the FHA explicitly refuses to insure HECMs on co-ops.

## The New York Legislative Fix

After years of lobbying, New York State finally passed a law allowing seniors to obtain reverse mortgages on co-op apartments. 

However, because the federal FHA still refuses to insure them, **you cannot get a standard HECM on a New York co-op.** 

Instead, you must apply for a **proprietary reverse mortgage** (often a Jumbo loan) offered by a private lender that has tailored a specific legal product for the New York co-op market. 

## The Board Approval Hurdle

Even though the state law allows it, the most difficult hurdle remains your Co-Op Board.

Co-op boards are notoriously strict and possess immense power over who can buy, sell, or finance units in the building. A private reverse mortgage lender will not approve your loan unless the Co-Op Board signs a recognition agreement acknowledging the lender's lien against your shares. 

Many conservative co-op boards are terrified of reverse mortgages and will flatly refuse to sign the agreement, effectively killing the deal. Before spending money on an appraisal, you must speak with your co-op board president to ensure they are willing to cooperate with a reverse mortgage lender.
"""
    },
    {
        "slug": "reverse-mortgages-in-arizona-snowbird-rules",
        "title": "Reverse Mortgages in Arizona: Snowbird Occupancy Rules",
        "description": "How the FHA primary residence rules apply to snowbirds who split their time between Arizona and a northern state.",
        "category": "state-guides",
        "date": "2024-01-28",
        "takeaways": [
            "A reverse mortgage property must be your primary residence (occupying it for 6+ months a year).",
            "Snowbirds must track their days carefully to avoid defaulting on the loan.",
            "Annual occupancy certifications are strictly enforced by servicers."
        ],
        "content": """
Arizona is a massive market for reverse mortgages, largely driven by retirees moving to the sunbelt. However, a huge portion of Arizona's senior population consists of "snowbirds"—people who live in Arizona during the winter and return to northern states (or Canada) during the brutal summer months.

This lifestyle creates a massive point of friction with the FHA's reverse mortgage rules.

## The "Majority of the Year" Rule

To maintain a Home Equity Conversion Mortgage (HECM) in good standing, the home must be your primary residence. 

The FHA defines a primary residence as the home where you live for **the majority of the calendar year (at least 183 days).**

If you own a home in Scottsdale, Arizona, and a home in Minneapolis, Minnesota, you cannot have a reverse mortgage on both. You must choose one to be your primary residence. 

If you take out a reverse mortgage on your Scottsdale home, you must physically live in it for at least 6 months and 1 day out of every year. If you stay in Minnesota for 7 months, your Arizona home becomes a secondary vacation home in the eyes of the FHA. 

## Annual Occupancy Certificates

The lender does not just take your word for it at closing. 

Every single year, on the anniversary of your loan, the loan servicer will mail you an **Annual Occupancy Certificate**. You must sign this legal document, under penalty of federal perjury, swearing that the Arizona home is still your primary residence.

If you ignore this letter because it was forwarded to your Minnesota address and you missed the deadline, the servicer will assume you have abandoned the property. They will declare the loan Due and Payable and begin the foreclosure process.

## Proving Occupancy

If the lender suspects you are not meeting the occupancy requirements, they will demand proof. They will ask to see:
- Your driver's license (which must show the Arizona address).
- Your voter registration.
- Where you file your state income taxes.
- Utility bills showing consistent usage during the required 6 months.

If you are a true snowbird, a reverse mortgage is perfectly fine, but you must meticulously track your calendar to ensure you spend at least 183 days in the house securing the loan.
"""
    },
    {
        "slug": "reverse-mortgage-solar-panels",
        "title": "Can You Get a Reverse Mortgage on a Home with Solar Panels?",
        "description": "Understand how leased vs. owned solar panels affect your home appraisal and reverse mortgage approval.",
        "category": "property-types",
        "date": "2024-01-30",
        "takeaways": [
            "Homes with owned solar panels easily qualify and appraise for higher values.",
            "Homes with leased solar panels require the lender to review the lease contract.",
            "PACE/HERO solar loans placed as tax liens must be paid off before closing."
        ],
        "content": """
As energy costs soar, millions of seniors are installing solar panels on their roofs. When it comes time to apply for a reverse mortgage, those solar panels can either be a massive benefit or a deal-killing legal nightmare, depending entirely on how they were financed.

## Scenario 1: You Own the Solar Panels Outright

If you paid cash for your solar panels, or if you took out a personal unsecured loan and the panels belong to you, congratulations. 

The FHA fully supports homes with owned solar panels. Furthermore, the FHA appraiser will add significant value to your home appraisal because the panels are a permanent fixture that generates energy. A higher appraised value means you can borrow more money from your reverse mortgage.

## Scenario 2: You Lease the Solar Panels

If a solar company installed the panels for "free" and you pay a monthly lease fee for the power, things get complicated. 

Because you do not own the panels, the solar company usually files a UCC-1 fixture filing on your property title. This alerts the world that they own the equipment on your roof.

To approve a reverse mortgage, the FHA requires your lender to review the solar lease contract. The lease must explicitly state that if your home is foreclosed upon, the solar company will not block the transfer of the property and will simply remove their equipment or negotiate a new lease with the buyer. Most major solar companies have standard subordination agreements ready for this exact scenario, but it will delay your loan closing.

## Scenario 3: PACE or HERO Loans (The Deal Killers)

The biggest danger involves **PACE (Property Assessed Clean Energy)** or **HERO** loans. 

These are municipal programs that allow you to finance solar panels by attaching the loan directly to your county property tax bill. 

The FHA strictly forbids reverse mortgages on homes with active PACE or HERO assessments. Why? Because property tax liens take priority over the FHA's mortgage lien. If the home goes into foreclosure, the county would get paid for the solar panels before the FHA gets paid for the mortgage. 

If you have a PACE loan, you must use a portion of your reverse mortgage proceeds to pay off the PACE loan in full at closing.
"""
    },
    {
        "slug": "what-is-repair-rider-set-aside",
        "title": "What is a Set-Aside for Property Repairs (Repair Rider)?",
        "description": "Learn what happens when an FHA appraiser requires mandatory repairs before your reverse mortgage can close.",
        "category": "process",
        "date": "2024-02-01",
        "takeaways": [
            "FHA appraisers enforce strict health and safety standards on the home.",
            "Minor repairs can be completed after closing using a Repair Set-Aside.",
            "The lender holds back 150% of the estimated repair cost from your loan proceeds."
        ],
        "content": """
The Federal Housing Administration (FHA) insures your reverse mortgage, which means your home is their collateral. Because of this, the FHA requires the home to meet strict Minimum Property Standards (MPS) regarding health, safety, and structural integrity.

When the FHA appraiser inspects your home, they are not just looking at the value; they are looking for peeling lead paint, a failing roof, exposed wiring, or a broken HVAC system.

What happens if the appraiser flags these issues? Do you have to pay out of pocket to fix them before you can get the loan?

## The Repair Set-Aside Solution

If the repairs are relatively minor (typically under $5,000) and do not pose an immediate, catastrophic threat to the structure, the FHA allows the loan to close using a **Repair Set-Aside (Repair Rider)**.

You do not have to pay for the repairs out of pocket before closing. Instead, you agree to fix the issues *after* the loan closes, using the money from the reverse mortgage itself.

## How the Math Works

To guarantee the work gets done, the lender will freeze a portion of your reverse mortgage funds. The FHA requires lenders to hold back **150% of the estimated repair cost.**

**Example:**
- The appraiser notes peeling paint and a broken window.
- The contractor estimates it will cost $2,000 to fix.
- At closing, the lender sets aside $3,000 (150% of $2k) in a frozen account.
- You receive the rest of your reverse mortgage funds.
- You have up to 6 months to hire a contractor and complete the repairs.
- Once the repairs are done, the appraiser returns for a final inspection.
- The lender pays the contractor the $2,000, and the remaining $1,000 is released back into your available line of credit.

## Major Structural Issues

Repair Set-Asides are only for minor to moderate issues. If the appraiser determines the home has a sinking foundation, a roof that is actively caving in, or an active termite infestation destroying the load-bearing walls, the FHA will not allow a Repair Set-Aside. 

In these severe cases, the home is deemed uninsurable. You must find a way to finance and complete the repairs yourself, out of pocket, before the reverse mortgage can proceed to closing.
"""
    },
    {
        "slug": "how-to-cancel-reverse-mortgage-rescission",
        "title": "How to Cancel a Reverse Mortgage Application (Rescission Period)",
        "description": "Understand your legal right to back out of a reverse mortgage, including the mandatory 3-day right of rescission.",
        "category": "legal",
        "date": "2024-02-03",
        "takeaways": [
            "You can cancel a reverse mortgage application at any time before closing without owing loan fees.",
            "Federal law grants a 3-day Right of Rescission after closing to cancel the deal.",
            "You must submit the cancellation in writing before the deadline expires."
        ],
        "content": """
A reverse mortgage is a massive financial commitment. It is not uncommon for seniors to get halfway through the process and get cold feet, or for a family member to suddenly offer to loan them the money instead.

If you have started the process, how easily can you back out?

## Canceling Before Closing

**You can walk away from a reverse mortgage application at any time prior to signing the final closing documents.** 

The lender cannot force you to close the loan. Furthermore, the lender cannot charge you for origination fees, title insurance, or FHA mortgage insurance if the loan does not close.

The only money you will lose is the out-of-pocket expenses you paid to third parties during the process. For example, if you paid $500 for the FHA appraisal and $125 for HUD counseling, those fees are non-refundable because the services were completed. 

## The 3-Day Right of Rescission

What happens if you sit at the closing table, sign the massive stack of legal documents, and wake up in a cold sweat the next morning regretting your decision?

Under the federal Truth in Lending Act (TILA), anyone taking out a mortgage on their primary residence is granted a **3-Day Right of Rescission**.

This means you have three full business days (excluding Sundays and federal holidays) after signing the closing documents to cancel the transaction entirely, with absolutely no penalty.

Because of this law, the lender will not actually distribute your cash on the day you sign. They hold the funds in escrow. Once the midnight deadline on the third business day passes, the loan officially "funds," and the money is wired to your bank account.

## How to Exercise the Right of Rescission

If you decide to cancel during that 3-day window, you cannot simply call your loan officer and leave a voicemail. 

You must notify the lender **in writing**. At closing, you will be handed a specific "Notice of Right to Cancel" form. You must sign this form, date it, and ensure it is delivered to the lender (via certified mail, fax, or hand delivery) before the midnight deadline. 

Once the three days have passed and the loan has funded, you can no longer cancel. To get out of the loan at that point, you would have to pay off the entire balance (including all the closing costs that were financed into the loan).
"""
    },
    {
        "slug": "reverse-mortgage-vs-sale-leaseback",
        "title": "Reverse Mortgage vs. Sale-Leaseback Agreements",
        "description": "Compare a standard reverse mortgage to residential sale-leaseback programs, exploring the risks of selling your home to an investor.",
        "category": "alternatives",
        "date": "2024-02-05",
        "takeaways": [
            "A reverse mortgage allows you to retain ownership of your home.",
            "A sale-leaseback involves selling your home to an investor and renting it back.",
            "Sale-leasebacks strip you of homeownership protections and expose you to eviction."
        ],
        "content": """
As property values have skyrocketed, a new industry of Wall Street investors and private equity firms has emerged, targeting cash-poor seniors. They advertise a product called a **Sale-Leaseback**.

The marketing pitch sounds similar to a reverse mortgage: *Get the cash out of your equity without having to move out of your house.*

However, the legal mechanics—and the risks—are completely different.

## How a Reverse Mortgage Works

With a Home Equity Conversion Mortgage (HECM), you take out a loan against your equity.
- **Ownership:** You remain the legal owner on the deed.
- **Appreciation:** If the home value goes up, you (or your heirs) keep that profit.
- **Security:** As long as you pay property taxes and insurance, you cannot be evicted. The FHA guarantees your right to live there for life.

## How a Sale-Leaseback Works

With a sale-leaseback, you are not taking out a loan. You are **selling your home** to a private investment firm.
- **Ownership:** You surrender the deed. The investor is the new owner. You are now a tenant.
- **The Cash:** The investor pays you cash for the home (often below market value).
- **The Catch:** You sign a lease agreeing to pay the investor monthly rent to continue living in the house you used to own.

## The Massive Risks of Sale-Leasebacks

While sale-leasebacks can close faster than a heavily regulated FHA reverse mortgage, they are incredibly dangerous for seniors on fixed incomes.

1. **Eviction Risk:** You are now a renter. If your rent goes up in three years and you can no longer afford it, the investor will evict you from the home you lived in for 30 years. 
2. **Loss of Appreciation:** Because you no longer own the home, any future appreciation belongs to the Wall Street firm, not your heirs.
3. **No FHA Protections:** Reverse mortgages are heavily regulated by the federal government to protect seniors. Sale-leasebacks are largely unregulated real estate transactions.

A sale-leaseback should only be considered as an absolute last resort if you cannot qualify for a reverse mortgage due to credit failures, or if the home does not meet FHA property standards. If you have the choice, retaining ownership via a reverse mortgage is vastly safer.
"""
    }
]

for article in articles:
    filepath = os.path.join('_src', '_content', 'articles', f"{article['slug']}.md")
    os.makedirs(os.path.dirname(filepath), exist_ok=True)
    
    frontmatter = {
        'title': article['title'],
        'description': article['description'],
        'slug': article['slug'],
        'category': article['category'],
        'date': article['date'],
        'takeaways': article['takeaways']
    }
    
    with open(filepath, 'w', encoding='utf-8') as f:
        f.write('---\n')
        yaml.dump(frontmatter, f, sort_keys=False)
        f.write('---\n\n')
        f.write(article['content'].strip())

print("Created 10 new articles for Batch 5.")
